site_name: AI for Security

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  icon:
  logo: 'assets/logo_white.png'
  favicon: 'assets/favicon.ico'

extra:
  search:
    language: 'jp'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
